list_user:
  controller: Controller\UserController:listUserAction

list_user:
  controller: Controller\UserController:showUserAction

list_user:
  controller: Controller\UserController:addUser

list_user:
  controller: Controller\UserController:deleteUser

list_user:
  controller: Controller\UserController:logUser