list_user:
  controller: Website\Controller\UserController:listUserAction

show_user:
  controller: Website\Controller\UserController:showUserAction

add_user:
  controller: Website\Controller\UserController:addUser

delete_user:
  controller: Website\Controller\UserController:deleteUser

log_user:
  controller: Website\Controller\UserController:logUser

test_user:
  controller: Website\Controller\UserController:test

home:
  controller: Website\Controller\homeController:homeAction